<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Customer Report - {{ date('Y-m-d') }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .summary-table th, .summary-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .summary-table th { background-color: #f2f2f2; }
        .customers-table { width: 100%; border-collapse: collapse; }
        .customers-table th, .customers-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .customers-table th { background-color: #f2f2f2; }
        .footer { margin-top: 30px; text-align: right; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Customer Report</h1>
        <p>Generated on: {{ $generatedAt }}</p>
    </div>

    @if(in_array('summary', $sections))
    <h2>Customer Summary</h2>
    <table class="summary-table">
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Total Customers</td>
            <td>{{ $customerActivity->total_customers }}</td>
        </tr>
        <tr>
            <td>Active Customers</td>
            <td>{{ $customerActivity->active_customers }}</td>
        </tr>
        <tr>
            <td>New Customers (30 days)</td>
            <td>{{ $customerActivity->new_customers }}</td>
        </tr>
        <tr>
            <td>Average Customer Value</td>
            <td>{{ $currencySymbol }}{{ number_format($avgCustomerValue, 2) }}</td>
        </tr>
    </table>
    @endif

    @if(in_array('top_customers', $sections))
    <h2>Top Customers by Spending</h2>
    <table class="customers-table">
        <thead>
            <tr>
                @if(in_array('customer_name', $columns))<th>Customer Name</th>@endif
                @if(in_array('email', $columns))<th>Email</th>@endif
                @if(in_array('phone', $columns))<th>Phone</th>@endif
                @if(in_array('total_orders', $columns))<th>Total Orders</th>@endif
                @if(in_array('total_spent', $columns))<th>Total Spent</th>@endif
                @if(in_array('avg_order_value', $columns))<th>Avg. Order Value</th>@endif
            </tr>
        </thead>
        <tbody>
            @foreach($topCustomers as $customer)
            <tr>
                @if(in_array('customer_name', $columns))<td>{{ $customer->name }}</td>@endif
                @if(in_array('email', $columns))<td>{{ $customer->email ?? 'No email' }}</td>@endif
                @if(in_array('phone', $columns))<td>{{ $customer->phone ?? 'No phone' }}</td>@endif
                @if(in_array('total_orders', $columns))<td>{{ $customer->sales_count }}</td>@endif
                @if(in_array('total_spent', $columns))<td>{{ $currencySymbol }}{{ number_format($customer->total_spent, 2) }}</td>@endif
                @if(in_array('avg_order_value', $columns))<td>{{ $currencySymbol }}{{ number_format($customer->sales_count > 0 ? $customer->total_spent / $customer->sales_count : 0, 2) }}</td>@endif
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        <p>Generated by POS System</p>
    </div>
</body>
</html>