<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Report - {{ date('Y-m-d') }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .summary-table th, .summary-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .summary-table th { background-color: #f2f2f2; }
        .category-table { width: 100%; border-collapse: collapse; }
        .category-table th, .category-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .category-table th { background-color: #f2f2f2; }
        .footer { margin-top: 30px; text-align: right; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inventory Report</h1>
        <p>Generated on: {{ $generatedAt }}</p>
    </div>

    @if(in_array('summary', $sections))
    <h2>Inventory Summary</h2>
    <table class="summary-table">
        <tr>
            <th>Metric</th>
            <th>Value</th>
        </tr>
        <tr>
            <td>Total Products</td>
            <td>{{ $inventorySummary->total_products }}</td>
        </tr>
        <tr>
            <td>Total Stock</td>
            <td>{{ $inventorySummary->total_stock }}</td>
        </tr>
        <tr>
            <td>Total Value</td>
            <td>{{ $currencySymbol }}{{ number_format($inventorySummary->total_value, 2) }}</td>
        </tr>
        <tr>
            <td>Low Stock Items</td>
            <td>{{ $inventorySummary->low_stock }}</td>
        </tr>
        <tr>
            <td>Out of Stock Items</td>
            <td>{{ $inventorySummary->out_of_stock }}</td>
        </tr>
    </table>
    @endif

    @if(in_array('categories', $sections))
    <h2>Inventory by Category</h2>
    <table class="category-table">
        <thead>
            <tr>
                @if(in_array('category', $columns))<th>Category</th>@endif
                @if(in_array('total_stock', $columns))<th>Total Stock</th>@endif
                @if(in_array('total_value', $columns))<th>Total Value</th>@endif
                @if(in_array('avg_value', $columns))<th>Average Value per Item</th>@endif
            </tr>
        </thead>
        <tbody>
            @foreach($inventoryByCategory as $category)
            <tr>
                @if(in_array('category', $columns))<td>{{ $category['name'] }}</td>@endif
                @if(in_array('total_stock', $columns))<td>{{ $category['total_stock'] }}</td>@endif
                @if(in_array('total_value', $columns))<td>{{ $currencySymbol }}{{ number_format($category['total_value'], 2) }}</td>@endif
                @if(in_array('avg_value', $columns))<td>{{ $currencySymbol }}{{ number_format($category['average_value'], 2) }}</td>@endif
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td @if(count($columns) > 1) colspan="{{ count($columns) - 1 }}" @endif><strong>Total</strong></td>
                <td><strong>{{ $currencySymbol }}{{ number_format($inventorySummary->total_value, 2) }}</strong></td>
            </tr>
        </tfoot>
    </table>
    @endif

    <div class="footer">
        <p>Generated by POS System</p>
    </div>
</body>
</html>